// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0CMC1qwpDE0FJUnvlH2wdHgRiGDmqsA',
    appId: '1:639520183995:web:dcbcf62368769c4b403b9e',
    messagingSenderId: '639520183995',
    projectId: 'trip-75cc0',
    authDomain: 'trip-75cc0.firebaseapp.com',
    storageBucket: 'trip-75cc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EY8FaxMI3Y-kDJvvOPKnFZdB5hPP1Fs',
    appId: '1:639520183995:android:9509d6b292a21e28403b9e',
    messagingSenderId: '639520183995',
    projectId: 'trip-75cc0',
    storageBucket: 'trip-75cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Wbyf4s1AqKlLH-3teKs-qcJFE4264Ag',
    appId: '1:639520183995:ios:229ff3270e0a96cc403b9e',
    messagingSenderId: '639520183995',
    projectId: 'trip-75cc0',
    storageBucket: 'trip-75cc0.appspot.com',
    iosBundleId: 'com.example.trip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Wbyf4s1AqKlLH-3teKs-qcJFE4264Ag',
    appId: '1:639520183995:ios:f0a8eb4052ea0639403b9e',
    messagingSenderId: '639520183995',
    projectId: 'trip-75cc0',
    storageBucket: 'trip-75cc0.appspot.com',
    iosBundleId: 'com.example.trip.RunnerTests',
  );
}
